// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StringConverter.Data;

#nullable disable

namespace StringConverter.Migrations
{
    [DbContext(typeof(StringConverterDbContext))]
    [Migration("20230712180621_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StringConverter.Models.Domain.TblConvertString", b =>
                {
                    b.Property<Guid>("UserIDpk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserIDpk");

                    b.ToTable("TblConvertStrings");
                });

            modelBuilder.Entity("StringConverter.Models.Domain.User", b =>
                {
                    b.Property<int>("usaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usaId"));

                    b.Property<string>("usaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usaPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usaId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
